# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: P:/IUP/Projekty/Laby/IUP_Laby/VGA/VGA.srcs/sources_1/ip/vga_bitmap/vga_bitmap.xci
# IP: The module: 'vga_bitmap' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: p:/IUP/Projekty/Laby/IUP_Laby/VGA/VGA.gen/sources_1/ip/vga_bitmap/vga_bitmap_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'vga_bitmap'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: P:/IUP/Projekty/Laby/IUP_Laby/VGA/VGA.srcs/sources_1/ip/vga_bitmap/vga_bitmap.xci
# IP: The module: 'vga_bitmap' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: p:/IUP/Projekty/Laby/IUP_Laby/VGA/VGA.gen/sources_1/ip/vga_bitmap/vga_bitmap_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'vga_bitmap'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
